### ISSUE TITLE
[New] Logo Red Ventures

### ISSUE THREAD

**Issue by cyz** [womendevsummit/womendevsummit.github.io#7]
@Camilafernandes 
por favor, adicione o logo da red ventures, patrocinador destaque (mesmo tamanho de Microsoft e CUBO).
Link: https://www.redventures.com/
![RV-Logotype](https://user-images.githubusercontent.com/2198735/76040670-bcddac80-5f2e-11ea-8fdb-b83c386e2fa1.png)

**Comment by Camilafernandes** [comment]
Incluido
